/*
 *  cross_stack_parity.rs
 *  WebARKitLib-rs
 *
 *  This file is part of WebARKitLib-rs - WebARKit.
 *
 *  WebARKitLib-rs is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  WebARKitLib-rs is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with WebARKitLib-rs.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As a special exception, the copyright holders of this library give you
 *  permission to link this library with independent modules to produce an
 *  executable, regardless of the license terms of these independent modules, and to
 *  copy and distribute the resulting executable under terms of your choice,
 *  provided that you also meet, for each linked independent module, the terms and
 *  conditions of the license of that module. An independent module is a module
 *  which is neither derived from nor based on this library. If you modify this
 *  library, you may extend this exception to your version of the library, but you
 *  are not obligated to do so. If you do not wish to do so, delete this exception
 *  statement from your version.
 *
 *  Copyright 2026 WebARKit.
 *
 *  Author(s): Walter Perdan @kalwalt https://github.com/kalwalt
 *
 */

//! Cross-stack parity gate (`jsartoolkitNFT#584` Track 2 / refs #166 Track B / #170).
//!
//! For each fixture in [`tools/jsartoolkitnft-bridge/expected-js.json`],
//! this test runs the **C++ FFI backend** (`CppFreakMatcher`) and the
//! **pure-Rust backend** (`RustFreakMatcher`) on the same image and
//! compares the resulting 3×4 KPM camera pose against the JS-stack
//! reference recorded in the sidecar (jsartoolkitNFT-Node's
//! `getNFTMarker` event output).
//!
//! ## What this test detects
//!
//! - **Tier-1**: matched_id agreement between all three stacks
//!   (Rust, C++ FFI, JS).
//! - **Element-wise pose drift**: max absolute difference between
//!   each pair's pose, separated into rotation (dimensionless) and
//!   translation (mm) elements. Generous epsilons absorb the
//!   current cross-stack envelope; CI failures here mean either a
//!   real regression in one of the stacks or that one of the stacks
//!   has been rebuilt / changed in a way that shifts the JS reference.
//!
//! ## Sidecar generation
//!
//! The JS sidecar is regenerated by running:
//!
//! ```sh
//! cd tools/jsartoolkitnft-bridge
//! npm install
//! npm run regen        # writes expected-js.json
//! ```
//!
//! Commit the new `expected-js.json` together with whatever change
//! prompted the regen (e.g. bumping the `@webarkit/jsartoolkit-nft`
//! dependency after #170's C++ side ships).
//!
//! ## Why Linux-only
//!
//! The C++ FFI matched_id and pose are platform-sensitive until both
//! halves of #170 land — see `kpm_regression::EXPECTED_FULL_POSE`
//! for the same gating rationale. The JS sidecar's WASM is hermetic
//! across host platforms (the WASM bytes encode the compile-time
//! libc++ behavior), so the SIDECAR is portable; what's not
//! portable is the C++ FFI side of the comparison. Gating to Linux
//! matches the existing ffi-backend integration test convention.

#![cfg(all(feature = "ffi-backend", target_os = "linux"))]

use std::collections::BTreeMap;
use std::fs;
use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use serde::Deserialize;

use webarkitlib_rs::kpm::types::KpmRefDataSet;
use webarkitlib_rs::kpm::{CppFreakMatcher, KpmHandle, RustFreakMatcher};
use webarkitlib_rs::types::{ARParam, ARParamLT};

// ─────────────────────────────────────────────────────────────────────────
// Tolerances
// ─────────────────────────────────────────────────────────────────────────

/// Max absolute difference allowed between any pair of stacks on any
/// rotation element of the 3×4 pose. Rotation elements are
/// dimensionless and bounded by `[-1, 1]`, so 0.08 corresponds to
/// roughly a few degrees of equivalent rotation.
///
/// Sized to absorb:
/// - Inter-stack BHC-variance envelope (M9-2 §10) on the current
///   fixture set (~0.04 worst-case observed pre-#170 fixes).
/// - **Residual Emscripten-vs-native cross-stack arithmetic drift**
///   measured against `@webarkit/jsartoolkit-nft@1.10.0` (the first
///   post-#39 rebuild). On `pinball-demo.jpg`, JS-WASM and native
///   C++ agree on `matched_id` (the std::map fix worked) but the
///   resulting 3×4 pose drifts by ~0.058 on the worst rotation
///   element — attributable to Eigen SIMD codegen + libc++ vs
///   libstdc++/MSVC CRT math function differences propagating
///   through the RANSAC + ICP inner loops. The mirror of the
///   ~2.85 px residual cross-platform drift `absolute_corner_error`
///   absorbs via its 3.5 px epsilon (#172), just expressed in a
///   different metric.
///
/// 0.08 is `~1.4×` the worst observed diff — modest headroom without
/// being loose. Was 0.05 pre-#173-merge-prep; widened after seeing
/// the residual Emscripten-vs-native drift in the post-#39 JS
/// sidecar. Tightens further only when Emscripten's SIMD codegen
/// converges with native (out of scope for #170).
const POSE_ROT_TOL: f32 = 0.08;

/// Max absolute difference allowed between any pair of stacks on any
/// translation element of the 3×4 pose. Translation elements are in
/// **millimetres** at AR working distance (z ≈ 500-600 mm for the
/// pinball fixture), so 10 mm is roughly 2% relative tolerance.
const POSE_TRANS_TOL: f32 = 10.0;

// ─────────────────────────────────────────────────────────────────────────
// JSON sidecar schema (mirrors tools/jsartoolkitnft-bridge/expected-js.json)
// ─────────────────────────────────────────────────────────────────────────

#[derive(Deserialize, Debug)]
struct JsSidecar {
    #[allow(dead_code)]
    schema: u32,
    #[allow(dead_code)]
    generated_with: String,
    #[allow(dead_code)]
    generated_at: Option<String>,
    #[allow(dead_code)]
    notes: Option<String>,
    per_frame: BTreeMap<String, JsFrameEntry>,
}

#[derive(Deserialize, Debug)]
struct JsFrameEntry {
    /// Marker id loaded into jsartoolkitNFT (always 0 for our single-
    /// marker setup). Present even when `first_match` is missing.
    loaded_marker_id: i32,
    /// The first `getNFTMarker` event payload — has `id`, `pose`, etc.
    /// `None` if jsartoolkitNFT failed to lock onto the marker before
    /// the process loop finished.
    first_match: Option<JsFirstMatch>,
}

#[derive(Deserialize, Debug)]
struct JsFirstMatch {
    /// Marker id reported by getNFTMarker. Matches `loaded_marker_id`
    /// when the right marker was tracked.
    id: i32,
    #[allow(dead_code)]
    error: f32,
    #[allow(dead_code)]
    found: i32,
    /// 3×4 pose as a flat 12-element row-major array.
    pose: Vec<f32>,
}

// ─────────────────────────────────────────────────────────────────────────
// Backend drivers
// ─────────────────────────────────────────────────────────────────────────

/// Marker name + .fset3 file in `crates/core/examples/Data/`.
const MARKER_NAME: &str = "pinball";

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn data_dir() -> PathBuf {
    manifest_dir().join("examples").join("Data")
}

fn sidecar_path() -> PathBuf {
    manifest_dir()
        .join("..")
        .join("..")
        .join("tools")
        .join("jsartoolkitnft-bridge")
        .join("expected-js.json")
}

/// Decode a JPEG → grayscale luma + dims, matching the Rust gate's
/// preprocessing (BT.601 integer RGB→Y).
fn decode_jpeg_luma(path: &Path) -> (Vec<u8>, i32, i32) {
    let bytes = fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let mut decoder = jpeg_decoder::Decoder::new(Cursor::new(&bytes));
    let pixels = decoder.decode().expect("JPEG decode failed");
    let info = decoder.info().expect("no JPEG info");
    let w = info.width as i32;
    let h = info.height as i32;
    let luma: Vec<u8> = pixels
        .chunks_exact(3)
        .map(|rgb| ((rgb[0] as u32 * 77 + rgb[1] as u32 * 150 + rgb[2] as u32 * 29) >> 8) as u8)
        .collect();
    (luma, w, h)
}

/// Build a `KpmHandle` around a `Box<dyn FreakMatcherBackend>` constructor,
/// run a single query against `image`, and return the matched (3×4 pose,
/// page_no). Camera intrinsics come from `camera_para.dat` rescaled to
/// the image dimensions.
fn run_one_backend<F>(image_path: &Path, mk_backend: F) -> (Option<[[f32; 4]; 3]>, i32)
where
    F: FnOnce(i32, i32) -> Box<dyn webarkitlib_rs::kpm::FreakMatcherBackend>,
{
    // Load + rescale camera params.
    let cam_path = data_dir().join("camera_para.dat");
    let cam_bytes = fs::read(&cam_path).expect("read camera_para.dat");
    let mut cparam = ARParam::load(Cursor::new(&cam_bytes)).expect("parse camera_para.dat");

    let (luma, w, h) = decode_jpeg_luma(image_path);

    let sx = w as f64 / cparam.xsize as f64;
    let sy = h as f64 / cparam.ysize as f64;
    for col in 0..4 {
        cparam.mat[0][col] *= sx;
        cparam.mat[1][col] *= sy;
    }
    cparam.xsize = w;
    cparam.ysize = h;
    let cparam_lt = Arc::new(ARParamLT::new_basic(cparam));

    // Load .fset3 reference data.
    let fset3 = data_dir().join(format!("{MARKER_NAME}.fset3"));
    let mut ref_data = KpmRefDataSet::load(&fset3).expect("load .fset3");
    ref_data.change_page_no(
        webarkitlib_rs::kpm::ref_data_set::KPM_CHANGE_PAGE_NO_ALL_PAGES,
        0,
    );

    // Build handle + query.
    let mut handle = KpmHandle::new(w, h, Some(cparam_lt), mk_backend(w, h));
    handle.set_ref_data_set(ref_data).expect("set_ref_data_set");
    handle.kpm_matching(&luma).expect("kpm_matching");

    match handle.get_pose() {
        Some((pose, page_no, _err)) => (Some(*pose), page_no),
        None => (None, -1),
    }
}

// ─────────────────────────────────────────────────────────────────────────
// Pose comparison
// ─────────────────────────────────────────────────────────────────────────

/// Pretty-prints a 3x4 pose row.
fn fmt_pose_row(row: &[f32; 4]) -> String {
    format!(
        "[{:>10.6} {:>10.6} {:>10.6} {:>10.4}]",
        row[0], row[1], row[2], row[3]
    )
}

/// Compute element-wise pairwise diff between two 3×4 poses, return
/// `(max_rot_diff, max_trans_diff)`.
fn pose_diff(a: &[[f32; 4]; 3], b: &[[f32; 4]; 3]) -> (f32, f32) {
    let mut max_rot = 0.0_f32;
    let mut max_trans = 0.0_f32;
    for r in 0..3 {
        for c in 0..4 {
            let d = (a[r][c] - b[r][c]).abs();
            if c < 3 {
                // rotation
                if d > max_rot {
                    max_rot = d;
                }
            } else {
                // translation
                if d > max_trans {
                    max_trans = d;
                }
            }
        }
    }
    (max_rot, max_trans)
}

/// Inflate a flat 12-element vec into a 3×4 row-major matrix.
fn pose_from_flat(flat: &[f32]) -> [[f32; 4]; 3] {
    let mut out = [[0.0_f32; 4]; 3];
    assert_eq!(
        flat.len(),
        12,
        "JS pose: expected 12 elements, got {}",
        flat.len()
    );
    for r in 0..3 {
        for c in 0..4 {
            out[r][c] = flat[r * 4 + c];
        }
    }
    out
}

// ─────────────────────────────────────────────────────────────────────────
// Test
// ─────────────────────────────────────────────────────────────────────────

#[test]
fn test_cross_stack_parity_against_jsartoolkitnft() {
    let sidecar_bytes = fs::read(sidecar_path()).unwrap_or_else(|e| {
        panic!(
            "could not read JS sidecar at {}: {e}\n\
             Regenerate with:\n  \
             cd tools/jsartoolkitnft-bridge && npm install && npm run regen",
            sidecar_path().display()
        )
    });
    let sidecar: JsSidecar =
        serde_json::from_slice(&sidecar_bytes).expect("parse expected-js.json");

    println!();
    println!(
        "Cross-stack parity gate — {} fixture(s) (against jsartoolkitNFT-Node)",
        sidecar.per_frame.len()
    );

    let mut failures: Vec<String> = Vec::new();

    for (frame_name, js_entry) in &sidecar.per_frame {
        let js_first_match = match &js_entry.first_match {
            Some(m) => m,
            None => {
                println!("\n[{frame_name}] JS sidecar has no first_match — skipping");
                continue;
            }
        };
        let js_pose = pose_from_flat(&js_first_match.pose);
        let js_id = js_first_match.id;

        let image_path = data_dir().join(frame_name);
        if !image_path.exists() {
            // The bridge expects the fixture in examples/Data/; if it's
            // not there, the sidecar is stale relative to the source tree.
            failures.push(format!(
                "fixture image '{}' referenced by sidecar not found at {}",
                frame_name,
                image_path.display()
            ));
            continue;
        }

        // Drive both Rust backends.
        let (cpp_pose, cpp_page) = run_one_backend(&image_path, |w, h| {
            Box::new(CppFreakMatcher::new(w, h).expect("CppFreakMatcher::new"))
        });
        let (rust_pose, rust_page) = run_one_backend(&image_path, |w, h| {
            Box::new(RustFreakMatcher::new(w, h).expect("RustFreakMatcher::new"))
        });

        println!("\n[{frame_name}]");
        println!(
            "  matched_id:  JS={js_id}  CppFFI={cpp_page}  Rust={rust_page}  \
             (sidecar loaded_marker_id={})",
            js_entry.loaded_marker_id
        );

        // Tier-1 check: all three stacks should pick the same matched_id.
        if cpp_page != js_id {
            failures.push(format!(
                "{frame_name}: C++ FFI matched_id={cpp_page} differs from JS id={js_id}"
            ));
        }
        if rust_page != js_id {
            failures.push(format!(
                "{frame_name}: Rust matched_id={rust_page} differs from JS id={js_id}"
            ));
        }

        // Print all three pose rows so failures are loud.
        println!("  Pose row 0:");
        println!(
            "    JS    {}",
            fmt_pose_row(&[js_pose[0][0], js_pose[0][1], js_pose[0][2], js_pose[0][3]])
        );
        if let Some(p) = &cpp_pose {
            println!("    CppFFI {}", fmt_pose_row(&p[0]));
        }
        if let Some(p) = &rust_pose {
            println!("    Rust   {}", fmt_pose_row(&p[0]));
        }

        // Per-pair pose diff.
        let do_compare = |label: &str, pose: &[[f32; 4]; 3], failures: &mut Vec<String>| {
            let (rd, td) = pose_diff(pose, &js_pose);
            println!(
                "  {label} vs JS:  max rot diff = {rd:.6}, max trans diff = {td:.4} mm  \
                 (tol: rot {POSE_ROT_TOL:.3}, trans {POSE_TRANS_TOL:.2})"
            );
            if rd > POSE_ROT_TOL {
                failures.push(format!(
                    "{frame_name}: {label} rotation diff vs JS = {rd:.6} > {POSE_ROT_TOL}"
                ));
            }
            if td > POSE_TRANS_TOL {
                failures.push(format!(
                    "{frame_name}: {label} translation diff vs JS = {td:.4} > {POSE_TRANS_TOL}"
                ));
            }
        };

        match &cpp_pose {
            Some(p) => do_compare("CppFFI", p, &mut failures),
            None => failures.push(format!("{frame_name}: C++ FFI did not produce a pose")),
        }
        match &rust_pose {
            Some(p) => do_compare("Rust  ", p, &mut failures),
            None => failures.push(format!("{frame_name}: Rust did not produce a pose")),
        }
    }

    println!();
    assert!(
        failures.is_empty(),
        "{} cross-stack parity failure(s):\n  {}\n\
         If the JS sidecar is stale (e.g. jsartoolkitNFT was rebuilt), regenerate via:\n  \
         cd tools/jsartoolkitnft-bridge && npm install && npm run regen",
        failures.len(),
        failures.join("\n  ")
    );
}
