/*
 *  regression.rs
 *  WebARKitLib-rs
 *
 *  This file is part of WebARKitLib-rs - WebARKit.
 *
 *  WebARKitLib-rs is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  WebARKitLib-rs is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with WebARKitLib-rs.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As a special exception, the copyright holders of this library give you
 *  permission to link this library with independent modules to produce an
 *  executable, regardless of the license terms of these independent modules, and to
 *  copy and distribute the resulting executable under terms of your choice,
 *  provided that you also meet, for each linked independent module, the terms and
 *  conditions of the license of that module. An independent module is a module
 *  which is neither derived from nor based on this library. If you modify this
 *  library, you may extend this exception to your version of the library, but you
 *  are not obligated to do so. If you do not wish to do so, delete this exception
 *  statement from your version.
 *
 *  Copyright 2026 WebARKit.
 *
 *  Author(s): Walter Perdan @kalwalt https://github.com/kalwalt
 *
 */

//! KPM regression tests — numerical validation against C++ baseline.
//!
//! These tests compare Rust outputs to values generated by the C++
//! `kpm_dump_fixtures` tool in `benchmarks/c_benchmark/`. The fixture
//! data (JSON + hardcoded consts) was produced by running the C++ KPM
//! pipeline on `pinball-demo.jpg` and dumping the resulting poses, ICP
//! results, and correspondences.
//!
//! # Test matrix
//!
//! | Test                         | What it validates                              | Feature gate |
//! |------------------------------|------------------------------------------------|--------------|
//! | `test_fset3_load_structure`  | .fset3 binary I/O round-trip                   | none         |
//! | `test_full_pipeline_pose`    | Full kpmMatching pose vs C++ baseline           | ffi-backend  |
//! | `test_standalone_icp`        | ICP refinement on synthetic correspondences     | none         |
//! | `test_luminance_conversion`  | JPEG→luma conversion consistency                | none         |

#![allow(dead_code)]

use std::path::Path;

// ---------------------------------------------------------------------------
// C++ baseline constants (generated by kpm_dump_fixtures)
// ---------------------------------------------------------------------------

/// Synthetic 2D screen coordinates (6 inlier correspondences).
const SCREEN: &[[f32; 2]] = &[
    [423.971_863, 947.783_447],
    [581.893_188, 974.264_343],
    [740.726_746, 1_000.898_132],
    [466.511_871, 798.244_080],
    [619.929_932, 823.531_799],
    [805.780_334, 705.689_148],
];

/// Corresponding 3D world coordinates (planar, Z=0).
const WORLD: &[[f32; 3]] = &[
    [0.0, 0.0, 0.0],
    [50.0, 0.0, 0.0],
    [100.0, 0.0, 0.0],
    [0.0, 50.0, 0.0],
    [50.0, 50.0, 0.0],
    [100.0, 100.0, 0.0],
];

/// Full-pipeline pose from C++ kpmMatching (3x4 matrix, row-major).
const EXPECTED_FULL_POSE: [[f32; 4]; 3] = [
    [
        9.864_128_83e-01,
        1.622_414_74e-01,
        2.583_317_27e-02,
        -1.818_470_61e+02,
    ],
    [
        1.607_509_70e-01,
        -9.207_431_67e-01,
        -3.555_152_42e-01,
        6.390_821_08e+01,
    ],
    [
        -3.389_360_38e-02,
        3.548_375_37e-01,
        -9.343_134_16e-01,
        5.901_221_31e+02,
    ],
];

/// Full-pipeline reprojection error from C++.
const EXPECTED_FULL_ERROR: f32 = 6.303_418_16e+00;

/// ICP-refined pose from C++ (standalone ICP on the 6 correspondences above).
const EXPECTED_ICP_POSE: [[f32; 4]; 3] = [
    [
        9.864_128_83e-01,
        1.622_414_44e-01,
        2.583_362_53e-02,
        -1.818_470_61e+02,
    ],
    [
        1.607_510_89e-01,
        -9.207_431_67e-01,
        -3.555_152_42e-01,
        6.390_820_31e+01,
    ],
    [
        -3.389_316_80e-02,
        3.548_375_67e-01,
        -9.343_134_16e-01,
        5.901_221_31e+02,
    ],
];

/// ICP residual error from C++ (should be near zero for synthetic data).
const EXPECTED_ICP_ERROR: f32 = 1.977_796_95e-10;

/// Camera intrinsic matrix from camera_para.dat (3x4, after resize to 2000x1500).
const CAM_MAT: [[f64; 4]; 3] = [
    [1.904_266_90e+03, 0.0, 1.010_774_71e+03, 0.0],
    [0.0, 1.895_378_82e+03, 7.425_204_28e+02, 0.0],
    [0.0, 0.0, 1.0, 0.0],
];

// ---------------------------------------------------------------------------
// Helper: absolute tolerance comparison for pose matrices
// ---------------------------------------------------------------------------

fn assert_pose_near(label: &str, actual: &[[f32; 4]; 3], expected: &[[f32; 4]; 3], tol: f32) {
    for r in 0..3 {
        for c in 0..4 {
            let diff = (actual[r][c] - expected[r][c]).abs();
            assert!(
                diff <= tol,
                "{label}: pose[{r}][{c}] differs by {diff:.6e} \
                 (actual={:.6e}, expected={:.6e}, tol={tol:.1e})",
                actual[r][c],
                expected[r][c],
            );
        }
    }
}

// ===========================================================================
// Test 1: .fset3 load structure
// ===========================================================================

/// Validate that `KpmRefDataSet::load` parses pinball.fset3 correctly and
/// produces the exact same structure the C++ code does.
#[test]
fn test_fset3_load_structure() {
    use webarkitlib_kpm::types::KpmRefDataSet;

    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("examples")
        .join("data")
        .join("pinball.fset3");

    let ds = KpmRefDataSet::load(&path).expect("failed to load pinball.fset3");

    // From C++ output: 4850 total feature points.
    assert_eq!(ds.num, 4850, "expected 4850 ref points");
    assert_eq!(ds.ref_point.len(), 4850);

    // Single page with 9 pyramid images.
    assert_eq!(ds.page_num, 1, "expected 1 page");
    assert_eq!(ds.page_info.len(), 1);
    assert_eq!(ds.page_info[0].image_num, 9, "expected 9 pyramid images");

    // Feature counts per image match C++ log output.
    // ref_image_no is 0..8 (sequential index into pyramid), not the
    // arbitrary image_no stored in page_info.
    let expected_counts = [636, 648, 615, 607, 590, 540, 508, 437, 269];
    for (i, &expected) in expected_counts.iter().enumerate() {
        let count = ds
            .ref_point
            .iter()
            .filter(|rp| rp.ref_image_no == i as i32)
            .count();
        assert_eq!(
            count, expected,
            "pyramid level {i}: expected {expected} features, got {count}",
        );
    }

    // All features belong to the same page.
    let page_no = ds.page_info[0].page_no;
    assert!(ds.ref_point.iter().all(|rp| rp.page_no == page_no));

    // Descriptors are not all zeros.
    assert!(
        ds.ref_point[0].feature_vec.v.iter().any(|&b| b != 0),
        "first FREAK descriptor should not be all-zero"
    );
}

// ===========================================================================
// Test 2: Full pipeline pose (FFI backend required)
// ===========================================================================

/// Run the full kpmMatching pipeline on pinball-demo.jpg and compare the
/// resulting 3x4 pose matrix to the C++ baseline.
///
/// This test requires the `ffi-backend` feature because it delegates
/// feature extraction to the compiled C++ FreakMatcher library.
///
/// NOTE: Currently ignored — the full FFI pipeline integration (query →
/// match → pose) is not yet fully wired. The C++ baseline values are
/// preserved here for when the pipeline is complete. See issue #28.
#[cfg(feature = "ffi-backend")]
#[test]
#[ignore = "full FFI pipeline not yet wired end-to-end (issue #28)"]
fn test_full_pipeline_pose() {
    use std::sync::Arc;
    use webarkitlib_kpm::types::KpmRefDataSet;
    use webarkitlib_kpm::{CppFreakMatcher, KpmHandle};
    use webarkitlib_rs::types::{ARParam, ARParamLT};

    // Load camera parameters.
    let cam_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("benchmarks")
        .join("data")
        .join("camera_para.dat");
    let cam_file = std::fs::File::open(&cam_path).expect("failed to open camera_para.dat");
    let mut cparam =
        ARParam::load(std::io::BufReader::new(cam_file)).expect("failed to load camera_para.dat");

    // Load query image (JPEG → RGB → luma).
    let img_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("examples")
        .join("data")
        .join("pinball-demo.jpg");
    let jpeg_bytes = std::fs::read(&img_path).expect("failed to read pinball-demo.jpg");
    let mut decoder = jpeg_decoder::Decoder::new(std::io::Cursor::new(&jpeg_bytes));
    let pixels = decoder.decode().expect("JPEG decode failed");
    let info = decoder.info().unwrap();
    let (w, h) = (info.width as i32, info.height as i32);
    assert_eq!(w, 2000);
    assert_eq!(h, 1500);

    // Convert RGB → luma (BT.601).
    let luma: Vec<u8> = pixels
        .chunks_exact(3)
        .map(|rgb| ((rgb[0] as u32 * 77 + rgb[1] as u32 * 150 + rgb[2] as u32 * 29) >> 8) as u8)
        .collect();
    assert_eq!(luma.len(), (w * h) as usize);

    // Resize camera params to match image (arParamChangeSize equivalent).
    // Row 0 *= x_scale, Row 1 *= y_scale, Row 2 unchanged.
    let sx = w as f64 / cparam.xsize as f64;
    let sy = h as f64 / cparam.ysize as f64;
    for col in 0..4 {
        cparam.mat[0][col] *= sx;
        cparam.mat[1][col] *= sy;
    }
    cparam.xsize = w;
    cparam.ysize = h;

    let cparam_lt = Arc::new(ARParamLT::new_basic(cparam));

    // Load .fset3 reference data.
    let fset3_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("examples")
        .join("data")
        .join("pinball.fset3");
    let mut ref_data_set = KpmRefDataSet::load(&fset3_path).expect("failed to load pinball.fset3");

    // Change all pages to page 0 (matches C++ setup).
    ref_data_set.change_page_no(
        webarkitlib_kpm::ref_data_set::KPM_CHANGE_PAGE_NO_ALL_PAGES,
        0,
    );

    // Create KPM handle with C++ backend.
    let backend = CppFreakMatcher::new(w, h).expect("failed to create CppFreakMatcher");
    let mut handle = KpmHandle::new(w, h, Some(cparam_lt), Box::new(backend));
    handle
        .set_ref_data_set(ref_data_set)
        .expect("set_ref_data_set failed");

    // Run matching.
    handle.kpm_matching(&luma).expect("kpm_matching failed");

    // Extract best pose.
    let (pose, page_no, error) = handle
        .get_pose()
        .expect("kpm_matching should find a valid pose for pinball-demo.jpg");

    assert_eq!(page_no, 0, "matched page should be 0");

    // Compare pose to C++ baseline (tolerance: 1e-2 for full pipeline).
    assert_pose_near("full_pipeline", pose, &EXPECTED_FULL_POSE, 1e-2);

    // Error should be in the same ballpark.
    let error_diff = (error - EXPECTED_FULL_ERROR).abs();
    assert!(
        error_diff < 2.0,
        "full pipeline error differs by {error_diff:.4} \
         (actual={error:.4}, expected={EXPECTED_FULL_ERROR:.4})",
    );
}

// ===========================================================================
// Test 3: Standalone ICP refinement
// ===========================================================================

/// Run ICP refinement on 6 synthetic 2D↔3D correspondences extracted by
/// the C++ fixture generator. Compare the refined pose to the C++ ICP
/// baseline.
#[test]
fn test_standalone_icp() {
    use webarkitlib_rs::icp::{
        icp_create_handle, icp_delete_handle, icp_get_init_xw2xc_from_planar_data, icp_point,
        ICP2DCoordT, ICP3DCoordT, ICPDataT,
    };
    use webarkitlib_rs::types::ARdouble;

    let num = SCREEN.len();
    assert_eq!(num, WORLD.len());

    // Build ICP correspondences.
    let s_coord: Vec<ICP2DCoordT> = SCREEN
        .iter()
        .map(|s| ICP2DCoordT {
            x: s[0] as ARdouble,
            y: s[1] as ARdouble,
        })
        .collect();

    let w_coord: Vec<ICP3DCoordT> = WORLD
        .iter()
        .map(|w| ICP3DCoordT {
            x: w[0] as ARdouble,
            y: w[1] as ARdouble,
            z: w[2] as ARdouble,
        })
        .collect();

    // Use the camera matrix from the fixture.
    let mat_xc2u: [[ARdouble; 4]; 3] = CAM_MAT;

    // Compute initial pose from planar data.
    let mut init_mat = [[0.0 as ARdouble; 4]; 3];
    icp_get_init_xw2xc_from_planar_data(&mat_xc2u, &s_coord, &w_coord, num, &mut init_mat)
        .expect("icp_get_init_xw2xc_from_planar_data failed");

    // Create ICP handle and refine.
    let mut icp_handle = icp_create_handle(&mat_xc2u).expect("icp_create_handle failed");

    let icp_data = ICPDataT {
        screen_coord: s_coord,
        world_coord: w_coord,
    };

    let mut mat_xw2xc = [[0.0 as ARdouble; 4]; 3];
    let err = icp_point(
        unsafe { &*icp_handle },
        &icp_data,
        &init_mat,
        &mut mat_xw2xc,
    )
    .expect("icp_point failed");

    let _ = icp_delete_handle(&mut icp_handle);

    // Convert f64 pose to f32 for comparison.
    let mut pose_f32 = [[0.0f32; 4]; 3];
    for r in 0..3 {
        for c in 0..4 {
            pose_f32[r][c] = mat_xw2xc[r][c] as f32;
        }
    }

    // Compare to C++ ICP baseline (tight tolerance: 1e-4).
    assert_pose_near("icp", &pose_f32, &EXPECTED_ICP_POSE, 1e-4);

    // ICP error should be very small for these synthetic correspondences.
    let err_f32 = err as f32;
    assert!(
        err_f32 < 1e-5,
        "ICP error too large: {err_f32:.6e} (expected < 1e-5, C++ baseline: {EXPECTED_ICP_ERROR:.6e})",
    );
}

// ===========================================================================
// Test 4: Luminance conversion consistency
// ===========================================================================

/// Decode pinball-demo.jpg to RGB, convert to luma using the same BT.601
/// formula as the C++ benchmark, and spot-check pixel values at known
/// locations.
#[test]
fn test_luminance_conversion() {
    let img_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("examples")
        .join("data")
        .join("pinball-demo.jpg");

    let jpeg_bytes = std::fs::read(&img_path).expect("failed to read pinball-demo.jpg");
    let mut decoder = jpeg_decoder::Decoder::new(std::io::Cursor::new(&jpeg_bytes));
    let pixels = decoder.decode().expect("JPEG decode failed");
    let info = decoder.info().unwrap();
    let w = info.width as usize;
    let h = info.height as usize;

    assert_eq!(w, 2000, "expected width 2000");
    assert_eq!(h, 1500, "expected height 1500");
    assert_eq!(pixels.len(), w * h * 3, "expected RGB pixel data");

    // Convert to luma using BT.601 (same integer formula as C++ stb_image + fixture generator).
    let luma: Vec<u8> = pixels
        .chunks_exact(3)
        .map(|rgb| ((rgb[0] as u32 * 77 + rgb[1] as u32 * 150 + rgb[2] as u32 * 29) >> 8) as u8)
        .collect();

    assert_eq!(luma.len(), w * h);

    // Spot-check: pixels at known locations are accessible.
    let _top_left = luma[0];
    let center = (h / 2) * w + (w / 2);
    let _center_val = luma[center];

    // Verify luma is not constant (real image should have variation).
    let min_luma = *luma.iter().min().unwrap();
    let max_luma = *luma.iter().max().unwrap();
    assert!(
        max_luma - min_luma > 50,
        "luma range too narrow: {min_luma}..{max_luma} — image may not have loaded correctly"
    );

    // Verify the luma histogram is not degenerate (>100 distinct values for a real photo).
    let mut hist = [0u32; 256];
    for &v in &luma {
        hist[v as usize] += 1;
    }
    let distinct = hist.iter().filter(|&&c| c > 0).count();
    assert!(
        distinct > 100,
        "only {distinct} distinct luma values — expected a real photograph"
    );
}
