/*
 *  kpm/mod.rs
 *  WebARKitLib-rs
 *
 *  This file is part of WebARKitLib-rs - WebARKit.
 *
 *  WebARKitLib-rs is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  WebARKitLib-rs is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with WebARKitLib-rs.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As a special exception, the copyright holders of this library give you
 *  permission to link this library with independent modules to produce an
 *  executable, regardless of the license terms of these independent modules, and to
 *  copy and distribute the resulting executable under terms of your choice,
 *  provided that you also meet, for each linked independent module, the terms and
 *  conditions of the license of that module. An independent module is a module
 *  which is neither derived from nor based on this library. If you modify this
 *  library, you may extend this exception to your version of the library, but you
 *  are not obligated to do so. If you do not wish to do so, delete this exception
 *  statement from your version.
 *
 *  Copyright 2026 WebARKit.
 *
 *  Author(s): Walter Perdan @kalwalt https://github.com/kalwalt
 *
 */

//! KPM (Key-Point Matching) / NFT (Natural Feature Tracking) layer,
//! ported from the C++ FreakMatcher library.
//!
//! This module provides a Rust interface to the FREAK-descriptor-based
//! feature matching pipeline used for planar image tracking. The matcher is
//! pluggable via the [`FreakMatcherBackend`] trait, with two implementations:
//!
//! - **pure Rust** ([`RustFreakMatcher`]) — the **default** since M9-3
//!   (#142). `cargo build` needs no C++ toolchain (no clang / libclang / cc).
//! - **`ffi-backend`** (`CppFreakMatcher`) — **opt-in**, delegates to the
//!   compiled C++ FreakMatcher static library through a thin `extern "C"`
//!   wrapper (`kpm_c_api.h`). Enable with `--features ffi-backend`. Used for
//!   cross-validation (`dual-mode`, `cross_stack_parity`), not required at
//!   runtime.
//!
//! ## Quick start
//!
//! Detect a marker in a grayscale frame with the pure-Rust backend:
//!
//! ```rust,ignore
//! use webarkitlib_rs::kpm::{KpmHandle, RustFreakMatcher};
//! use webarkitlib_rs::kpm::types::KpmRefDataSet;
//!
//! // Pure-Rust backend for a 640x480 camera frame.
//! let backend = RustFreakMatcher::new(640, 480)?;
//!
//! // Wrap it in a KpmHandle (the central coordinator).
//! let mut handle = KpmHandle::new(640, 480, None, Box::new(backend));
//!
//! // Load reference data generated by `nft_marker_gen` (.fset3).
//! let ref_data = KpmRefDataSet::load("marker.fset3")?;
//! handle.set_ref_data_set(ref_data)?;
//!
//! // Run detection on one frame; `luma` is width * height grayscale bytes.
//! handle.kpm_matching(&luma)?;
//! if let Some((pose, page_no, error)) = handle.get_pose() {
//!     // `pose` is a 3x4 camera pose matrix for `page_no`.
//! }
//! ```
//!
//! For a runnable end-to-end version (including AR2 tracking), see the
//! `simple_nft` example; for the browser, see `crates/wasm`'s
//! `WasmKpmHandle`.
//!
//! ## Module layout
//!
//! | Module           | Purpose |
//! |------------------|---------|
//! | [`backend`]      | [`FreakMatcherBackend`] trait and associated error / data types |
//! | [`handle`]       | [`KpmHandle`] struct — central coordinator for KPM operations |
//! | [`types`]        | Ported C structs ([`KpmRefDataSet`](types::KpmRefDataSet), etc.) |
//! | [`freak`]        | The pure-Rust FREAK pipeline — detector, descriptor, pyramids, Hough voting, homography, `VisualDatabase` |
//! | [`rust_backend`] | [`RustFreakMatcher`] (default) and `DualFreakMatcher` (parity-asserting) |
//! | `cpp_backend`    | `CppFreakMatcher` — FFI backend (only compiled with `--features ffi-backend`) |
//! | [`kpm_ffi`]      | Raw bindgen bindings (feature-gated) |
//! | [`matching`]     | [`MatchResult`](matching::MatchResult) wrapper |
//! | [`ref_data_set`] | [`RefDataSet`](ref_data_set::RefDataSet) collection |

// The KPM/NFT surface is the primary public API for library consumers, so it
// is held to full rustdoc coverage. This module tree is documented to 100%
// (#226); the warning is escalated to an error by CI's `clippy -D warnings`,
// so a new undocumented `pub` item here fails the build. The rest of the
// crate is still being back-filled — see #226 for the remaining modules.
#![warn(missing_docs)]

pub mod backend;
pub mod freak;
pub mod handle;
pub mod kpm_ffi;
pub mod matching;
pub mod ref_data_set;
pub mod rust_backend;
pub mod types;

#[cfg(feature = "ffi-backend")]
pub mod cpp_backend;

// Re-export key types for convenience.
pub use backend::QueryResult;
pub use backend::{FeaturePoint, FreakMatcherBackend, KpmError, Match, Point3d};
pub use handle::{KpmHandle, KpmPoseMode, KpmProcMode};
pub use ref_data_set::KpmCompMode;
pub use rust_backend::RustFreakMatcher;
pub use types::{Homography3x3, RefImage};

#[cfg(feature = "ffi-backend")]
pub use cpp_backend::CppFreakMatcher;

#[cfg(feature = "dual-mode")]
pub use rust_backend::DualFreakMatcher;
